#!/usr/bin/env python
# -*- coding: utf-8 -*-
#AUTOGENERATED FILE

from cheese.databaseControll.database import Database
from cheese.Logger import Logger
from python.models.Hotels import Hotels


class HotelsRepositoryImpl:

    @staticmethod
    def init():
        HotelsRepositoryImpl.table = "hotels"
        HotelsRepositoryImpl.scheme = "(id,package,p_nights,mail,web,phone,name,address)"
        HotelsRepositoryImpl.schemeNoBrackets = "id,package,p_nights,mail,web,phone,name,address"

    @staticmethod
    def convert(var):
        if (type(var) is int):
            var = int(var)
        elif (type(var) is float):
            var = float(var)
        return var

    @staticmethod
    def toJson(object):
        scheme = HotelsRepositoryImpl.schemeNoBrackets.split(",")
        ret = {}
        for s, o in zip(scheme, list(object)):
            try:
                ret[s] = int(o)
            except:
                ret[s] = o
        return ret

    @staticmethod
    def toModel(obj):
        model = Hotels()
        model.id = HotelsRepositoryImpl.convert(obj[0])
        model.package = HotelsRepositoryImpl.convert(obj[1])
        model.p_nights = HotelsRepositoryImpl.convert(obj[2])
        model.mail = HotelsRepositoryImpl.convert(obj[3])
        model.web = HotelsRepositoryImpl.convert(obj[4])
        model.phone = HotelsRepositoryImpl.convert(obj[5])
        model.name = HotelsRepositoryImpl.convert(obj[6])
        model.address = HotelsRepositoryImpl.convert(obj[7])
        return model

    @staticmethod
    def fromModel(model):
        tuple = (
            model.id,
            model.package,
            model.p_nights,
            model.mail,
            model.web,
            model.phone,
            model.name,
            model.address
        )
        return tuple

    @staticmethod
    def findAll(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select {HotelsRepositoryImpl.schemeNoBrackets} from hotels;")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(HotelsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def find(args):
        id = args[0]

        response = None
        try:
            db = Database()
            response = db.query(f"select {HotelsRepositoryImpl.schemeNoBrackets} from hotels where id={id};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        if (len(response) > 0):
            return HotelsRepositoryImpl.toModel(response[0])
        else: return None

    @staticmethod
    def findBy(args):
        columnName = args[0]
        value = args[1]

        response = None
        try:
            db = Database()
            response = db.query(f"select {HotelsRepositoryImpl.schemeNoBrackets} from hotels where {columnName}={value};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(HotelsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def findNewId(args):

        try:
            db = Database()
            db.commit(f"select max(id) from {HotelsRepositoryImpl.table};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def save(args):
        obj = HotelsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"insert into {HotelsRepositoryImpl.table} {HotelsRepositoryImpl.scheme} values {obj};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def update(args):
        obj = HotelsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"update {HotelsRepositoryImpl.table} set {HotelsRepositoryImpl.scheme} = {obj} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def delete(args):
        obj = HotelsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"delete from {HotelsRepositoryImpl.table} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

