#!/usr/bin/env python
# -*- coding: utf-8 -*-
#AUTOGENERATED FILE

from cheese.databaseControll.database import Database
from cheese.Logger import Logger
from python.models.RegisteredClubs import RegisteredClubs


class RegisteredClubsRepositoryImpl:

    @staticmethod
    def init():
        RegisteredClubsRepositoryImpl.table = "registered_clubs"
        RegisteredClubsRepositoryImpl.scheme = "(id,event_id,club_id,visa,checked)"
        RegisteredClubsRepositoryImpl.schemeNoBrackets = "id,event_id,club_id,visa,checked"

    @staticmethod
    def convert(var):
        if (type(var) is int):
            var = int(var)
        elif (type(var) is float):
            var = float(var)
        return var

    @staticmethod
    def toJson(object):
        scheme = RegisteredClubsRepositoryImpl.schemeNoBrackets.split(",")
        ret = {}
        for s, o in zip(scheme, list(object)):
            try:
                ret[s] = int(o)
            except:
                ret[s] = o
        return ret

    @staticmethod
    def toModel(obj):
        model = RegisteredClubs()
        model.id = RegisteredClubsRepositoryImpl.convert(obj[0])
        model.event_id = RegisteredClubsRepositoryImpl.convert(obj[1])
        model.club_id = RegisteredClubsRepositoryImpl.convert(obj[2])
        model.visa = RegisteredClubsRepositoryImpl.convert(obj[3])
        model.checked = RegisteredClubsRepositoryImpl.convert(obj[4])
        return model

    @staticmethod
    def fromModel(model):
        tuple = (
            model.id,
            model.event_id,
            model.club_id,
            model.visa,
            model.checked
        )
        return tuple

    @staticmethod
    def findAll(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredClubsRepositoryImpl.schemeNoBrackets} from registered_clubs;")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(RegisteredClubsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def find(args):
        id = args[0]

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredClubsRepositoryImpl.schemeNoBrackets} from registered_clubs where id={id};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        if (len(response) > 0):
            return RegisteredClubsRepositoryImpl.toModel(response[0])
        else: return None

    @staticmethod
    def findBy(args):
        columnName = args[0]
        value = args[1]

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredClubsRepositoryImpl.schemeNoBrackets} from registered_clubs where {columnName}={value};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(RegisteredClubsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def findNewId(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select max(id) from {RegisteredClubsRepositoryImpl.table};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        try: return int(response[0][0])
        except: return -1

    @staticmethod
    def save(args):
        obj = RegisteredClubsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"insert into {RegisteredClubsRepositoryImpl.table} {RegisteredClubsRepositoryImpl.scheme} values {obj};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def update(args):
        obj = RegisteredClubsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"update {RegisteredClubsRepositoryImpl.table} set {RegisteredClubsRepositoryImpl.scheme} = {obj} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def delete(args):
        obj = RegisteredClubsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"delete from {RegisteredClubsRepositoryImpl.table} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

