#!/usr/bin/env python
# -*- coding: utf-8 -*-
#AUTOGENERATED FILE

from cheese.databaseControll.database import Database
from cheese.Logger import Logger
from python.models.RegisteredHotels import RegisteredHotels


class RegisteredHotelsRepositoryImpl:

    @staticmethod
    def init():
        RegisteredHotelsRepositoryImpl.table = "registered_hotels"
        RegisteredHotelsRepositoryImpl.scheme = "(id,event_id,hotel_id)"
        RegisteredHotelsRepositoryImpl.schemeNoBrackets = "id,event_id,hotel_id"

    @staticmethod
    def convert(var):
        if (type(var) is int):
            var = int(var)
        elif (type(var) is float):
            var = float(var)
        return var

    @staticmethod
    def toJson(object):
        scheme = RegisteredHotelsRepositoryImpl.schemeNoBrackets.split(",")
        ret = {}
        for s, o in zip(scheme, list(object)):
            try:
                ret[s] = int(o)
            except:
                ret[s] = o
        return ret

    @staticmethod
    def toModel(obj):
        model = RegisteredHotels()
        model.id = RegisteredHotelsRepositoryImpl.convert(obj[0])
        model.event_id = RegisteredHotelsRepositoryImpl.convert(obj[1])
        model.hotel_id = RegisteredHotelsRepositoryImpl.convert(obj[2])
        return model

    @staticmethod
    def fromModel(model):
        tuple = (
            model.id,
            model.event_id,
            model.hotel_id
        )
        return tuple

    @staticmethod
    def findAll(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredHotelsRepositoryImpl.schemeNoBrackets} from registered_hotels;")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(RegisteredHotelsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def find(args):
        id = args[0]

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredHotelsRepositoryImpl.schemeNoBrackets} from registered_hotels where id={id};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        if (len(response) > 0):
            return RegisteredHotelsRepositoryImpl.toModel(response[0])
        else: return None

    @staticmethod
    def findBy(args):
        columnName = args[0]
        value = args[1]

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredHotelsRepositoryImpl.schemeNoBrackets} from registered_hotels where {columnName}={value};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(RegisteredHotelsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def findNewId(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select max(id) from {RegisteredHotelsRepositoryImpl.table};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        try: return int(response[0][0])
        except: return -1

    @staticmethod
    def save(args):
        obj = RegisteredHotelsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"insert into {RegisteredHotelsRepositoryImpl.table} {RegisteredHotelsRepositoryImpl.scheme} values {obj};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def update(args):
        obj = RegisteredHotelsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"update {RegisteredHotelsRepositoryImpl.table} set {RegisteredHotelsRepositoryImpl.scheme} = {obj} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def delete(args):
        obj = RegisteredHotelsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"delete from {RegisteredHotelsRepositoryImpl.table} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

