#!/usr/bin/env python
# -*- coding: utf-8 -*-
#AUTOGENERATED FILE

from cheese.databaseControll.database import Database
from cheese.Logger import Logger
from python.models.RegisteredTests import RegisteredTests


class RegisteredTestsRepositoryImpl:

    @staticmethod
    def init():
        RegisteredTestsRepositoryImpl.table = "registered_tests"
        RegisteredTestsRepositoryImpl.scheme = "(id,reg_jb_id,pcr,date)"
        RegisteredTestsRepositoryImpl.schemeNoBrackets = "id,reg_jb_id,pcr,date"

    @staticmethod
    def convert(var):
        if (type(var) is int):
            var = int(var)
        elif (type(var) is float):
            var = float(var)
        return var

    @staticmethod
    def toJson(object):
        scheme = RegisteredTestsRepositoryImpl.schemeNoBrackets.split(",")
        ret = {}
        for s, o in zip(scheme, list(object)):
            try:
                ret[s] = int(o)
            except:
                ret[s] = o
        return ret

    @staticmethod
    def toModel(obj):
        model = RegisteredTests()
        model.id = RegisteredTestsRepositoryImpl.convert(obj[0])
        model.reg_jb_id = RegisteredTestsRepositoryImpl.convert(obj[1])
        model.pcr = RegisteredTestsRepositoryImpl.convert(obj[2])
        model.date = RegisteredTestsRepositoryImpl.convert(obj[3])
        return model

    @staticmethod
    def fromModel(model):
        tuple = (
            model.id,
            model.reg_jb_id,
            model.pcr,
            model.date
        )
        return tuple

    @staticmethod
    def findAll(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredTestsRepositoryImpl.schemeNoBrackets} from registered_tests;")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(RegisteredTestsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def find(args):
        id = args[0]

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredTestsRepositoryImpl.schemeNoBrackets} from registered_tests where id={id};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        if (len(response) > 0):
            return RegisteredTestsRepositoryImpl.toModel(response[0])
        else: return None

    @staticmethod
    def findBy(args):
        columnName = args[0]
        value = args[1]

        response = None
        try:
            db = Database()
            response = db.query(f"select {RegisteredTestsRepositoryImpl.schemeNoBrackets} from registered_tests where {columnName}={value};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(RegisteredTestsRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def findNewId(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select max(id) from {RegisteredTestsRepositoryImpl.table};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        try: return int(response[0][0])
        except: return -1

    @staticmethod
    def save(args):
        obj = RegisteredTestsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"insert into {RegisteredTestsRepositoryImpl.table} {RegisteredTestsRepositoryImpl.scheme} values {obj};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def update(args):
        obj = RegisteredTestsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"update {RegisteredTestsRepositoryImpl.table} set {RegisteredTestsRepositoryImpl.scheme} = {obj} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def delete(args):
        obj = RegisteredTestsRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"delete from {RegisteredTestsRepositoryImpl.table} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

