#!/usr/bin/env python
# -*- coding: utf-8 -*-
#AUTOGENERATED FILE

from cheese.databaseControll.database import Database
from cheese.Logger import Logger
from python.models.Tokens import Tokens


class TokensRepositoryImpl:

    @staticmethod
    def init():
        TokensRepositoryImpl.table = "tokens"
        TokensRepositoryImpl.scheme = "(id,user_id,token,ip)"
        TokensRepositoryImpl.schemeNoBrackets = "id,user_id,token,ip"

    @staticmethod
    def convert(var):
        if (type(var) is int):
            var = int(var)
        elif (type(var) is float):
            var = float(var)
        return var

    @staticmethod
    def toJson(object):
        scheme = TokensRepositoryImpl.schemeNoBrackets.split(",")
        ret = {}
        for s, o in zip(scheme, list(object)):
            try:
                ret[s] = int(o)
            except:
                ret[s] = o
        return ret

    @staticmethod
    def toModel(obj):
        model = Tokens()
        model.id = TokensRepositoryImpl.convert(obj[0])
        model.user_id = TokensRepositoryImpl.convert(obj[1])
        model.token = TokensRepositoryImpl.convert(obj[2])
        model.ip = TokensRepositoryImpl.convert(obj[3])
        return model

    @staticmethod
    def fromModel(model):
        tuple = (
            model.id,
            model.user_id,
            model.token,
            model.ip
        )
        return tuple

    @staticmethod
    def findAll(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select {TokensRepositoryImpl.schemeNoBrackets} from tokens;")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(TokensRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def find(args):
        id = args[0]

        response = None
        try:
            db = Database()
            response = db.query(f"select {TokensRepositoryImpl.schemeNoBrackets} from tokens where id={id};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        if (len(response) > 0):
            return TokensRepositoryImpl.toModel(response[0])
        else: return None

    @staticmethod
    def findBy(args):
        columnName = args[0]
        value = args[1]

        response = None
        try:
            db = Database()
            response = db.query(f"select {TokensRepositoryImpl.schemeNoBrackets} from tokens where {columnName}={value};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(TokensRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def findNewId(args):

        try:
            db = Database()
            db.commit(f"select max(id) from {TokensRepositoryImpl.table};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def save(args):
        obj = TokensRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"insert into {TokensRepositoryImpl.table} {TokensRepositoryImpl.scheme} values {obj};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def update(args):
        obj = TokensRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"update {TokensRepositoryImpl.table} set {TokensRepositoryImpl.scheme} = {obj} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def delete(args):
        obj = TokensRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"delete from {TokensRepositoryImpl.table} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

