#!/usr/bin/env python
# -*- coding: utf-8 -*-
#AUTOGENERATED FILE

from cheese.databaseControll.database import Database
from cheese.Logger import Logger
from python.models.Users import Users


class UsersRepositoryImpl:

    @staticmethod
    def init():
        UsersRepositoryImpl.table = "users"
        UsersRepositoryImpl.scheme = "(id,rule_id,login,phone,full_name)"
        UsersRepositoryImpl.schemeNoBrackets = "id,rule_id,login,phone,full_name"

    @staticmethod
    def convert(var):
        if (type(var) is int):
            var = int(var)
        elif (type(var) is float):
            var = float(var)
        return var

    @staticmethod
    def toJson(object):
        scheme = UsersRepositoryImpl.schemeNoBrackets.split(",")
        ret = {}
        for s, o in zip(scheme, list(object)):
            try:
                ret[s] = int(o)
            except:
                ret[s] = o
        return ret

    @staticmethod
    def toModel(obj):
        model = Users()
        model.id = UsersRepositoryImpl.convert(obj[0])
        model.rule_id = UsersRepositoryImpl.convert(obj[1])
        model.login = UsersRepositoryImpl.convert(obj[2])
        model.phone = UsersRepositoryImpl.convert(obj[3])
        model.full_name = UsersRepositoryImpl.convert(obj[4])
        return model

    @staticmethod
    def fromModel(model):
        tuple = (
            model.id,
            model.rule_id,
            model.login,
            model.phone,
            model.full_name
        )
        return tuple

    @staticmethod
    def findAll(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select {UsersRepositoryImpl.schemeNoBrackets} from users;")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(UsersRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def find(args):
        id = args[0]

        response = None
        try:
            db = Database()
            response = db.query(f"select {UsersRepositoryImpl.schemeNoBrackets} from users where id={id};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        if (len(response) > 0):
            return UsersRepositoryImpl.toModel(response[0])
        else: return None

    @staticmethod
    def findBy(args):
        columnName = args[0]
        value = args[1]

        response = None
        try:
            db = Database()
            response = db.query(f"select {UsersRepositoryImpl.schemeNoBrackets} from users where {columnName}={value};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        resp = []
        for a in response:
            resp.append(UsersRepositoryImpl.toModel(a))
        return resp

    @staticmethod
    def findNewId(args):

        response = None
        try:
            db = Database()
            response = db.query(f"select max(id) from {UsersRepositoryImpl.table};")
            db.done()
        except Exception as e:
            Logger.fail("An error occurred while query request", str(e))

        if (response == None): return response
        try: return int(response[0][0])
        except: return -1

    @staticmethod
    def save(args):
        obj = UsersRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"insert into {UsersRepositoryImpl.table} {UsersRepositoryImpl.scheme} values {obj};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def update(args):
        obj = UsersRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"update {UsersRepositoryImpl.table} set {UsersRepositoryImpl.scheme} = {obj} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

    @staticmethod
    def delete(args):
        obj = UsersRepositoryImpl.fromModel(args[0])

        try:
            db = Database()
            db.commit(f"delete from {UsersRepositoryImpl.table} where id={obj[0]};")
            db.done()
            return True
        except Exception as e:
            Logger.fail("An error occurred while commit request", str(e))
            return False

