#!/usr/bin/env python
# -*- coding: utf-8 -*-

from datetime import datetime
import inspect

from cheese.resourceManager import ResMan
from cheese.databaseControll.database import Database

#REPOSITORIES
from cheese.repositories.BedRepositoryImpl import BedRepositoryImpl
from cheese.repositories.ClubsRepositoryImpl import ClubsRepositoryImpl
from cheese.repositories.EventsRepositoryImpl import EventsRepositoryImpl
from cheese.repositories.HotelsRepositoryImpl import HotelsRepositoryImpl
from cheese.repositories.JbRepositoryImpl import JbRepositoryImpl
from cheese.repositories.PasswordsRepositoryImpl import PasswordsRepositoryImpl
from cheese.repositories.RegisteredClubsRepositoryImpl import RegisteredClubsRepositoryImpl
from cheese.repositories.RegisteredHotelsRepositoryImpl import RegisteredHotelsRepositoryImpl
from cheese.repositories.RegisteredJbRepositoryImpl import RegisteredJbRepositoryImpl
from cheese.repositories.RegisteredTestsRepositoryImpl import RegisteredTestsRepositoryImpl
from cheese.repositories.RolesRepositoryImpl import RolesRepositoryImpl
from cheese.repositories.RoomsRepositoryImpl import RoomsRepositoryImpl
from cheese.repositories.TokensRepositoryImpl import TokensRepositoryImpl
from cheese.repositories.UsersRepositoryImpl import UsersRepositoryImpl


"""
File generated by Cheese Framework

Database query of Cheese Application
"""

class CheeseRepository:

    @staticmethod
    def findAll(args):
        userRepository = CheeseRepository.findUserRepository()
        args = CheeseRepository.getTypeOf(args)

        if (userRepository == "BedRepository"):
            return BedRepositoryImpl.findAll(args)
        elif (userRepository == "ClubsRepository"):
            return ClubsRepositoryImpl.findAll(args)
        elif (userRepository == "EventsRepository"):
            return EventsRepositoryImpl.findAll(args)
        elif (userRepository == "HotelsRepository"):
            return HotelsRepositoryImpl.findAll(args)
        elif (userRepository == "JbRepository"):
            return JbRepositoryImpl.findAll(args)
        elif (userRepository == "PasswordsRepository"):
            return PasswordsRepositoryImpl.findAll(args)
        elif (userRepository == "RegisteredClubsRepository"):
            return RegisteredClubsRepositoryImpl.findAll(args)
        elif (userRepository == "RegisteredHotelsRepository"):
            return RegisteredHotelsRepositoryImpl.findAll(args)
        elif (userRepository == "RegisteredJbRepository"):
            return RegisteredJbRepositoryImpl.findAll(args)
        elif (userRepository == "RegisteredTestsRepository"):
            return RegisteredTestsRepositoryImpl.findAll(args)
        elif (userRepository == "RolesRepository"):
            return RolesRepositoryImpl.findAll(args)
        elif (userRepository == "RoomsRepository"):
            return RoomsRepositoryImpl.findAll(args)
        elif (userRepository == "TokensRepository"):
            return TokensRepositoryImpl.findAll(args)
        elif (userRepository == "UsersRepository"):
            return UsersRepositoryImpl.findAll(args)
    @staticmethod
    def find(args):
        userRepository = CheeseRepository.findUserRepository()
        args = CheeseRepository.getTypeOf(args)

        if (userRepository == "BedRepository"):
            return BedRepositoryImpl.find(args)
        elif (userRepository == "ClubsRepository"):
            return ClubsRepositoryImpl.find(args)
        elif (userRepository == "EventsRepository"):
            return EventsRepositoryImpl.find(args)
        elif (userRepository == "HotelsRepository"):
            return HotelsRepositoryImpl.find(args)
        elif (userRepository == "JbRepository"):
            return JbRepositoryImpl.find(args)
        elif (userRepository == "PasswordsRepository"):
            return PasswordsRepositoryImpl.find(args)
        elif (userRepository == "RegisteredClubsRepository"):
            return RegisteredClubsRepositoryImpl.find(args)
        elif (userRepository == "RegisteredHotelsRepository"):
            return RegisteredHotelsRepositoryImpl.find(args)
        elif (userRepository == "RegisteredJbRepository"):
            return RegisteredJbRepositoryImpl.find(args)
        elif (userRepository == "RegisteredTestsRepository"):
            return RegisteredTestsRepositoryImpl.find(args)
        elif (userRepository == "RolesRepository"):
            return RolesRepositoryImpl.find(args)
        elif (userRepository == "RoomsRepository"):
            return RoomsRepositoryImpl.find(args)
        elif (userRepository == "TokensRepository"):
            return TokensRepositoryImpl.find(args)
        elif (userRepository == "UsersRepository"):
            return UsersRepositoryImpl.find(args)
    @staticmethod
    def findBy(args):
        userRepository = CheeseRepository.findUserRepository()
        args = CheeseRepository.getTypeOf(args)

        if (userRepository == "BedRepository"):
            return BedRepositoryImpl.findBy(args)
        elif (userRepository == "ClubsRepository"):
            return ClubsRepositoryImpl.findBy(args)
        elif (userRepository == "EventsRepository"):
            return EventsRepositoryImpl.findBy(args)
        elif (userRepository == "HotelsRepository"):
            return HotelsRepositoryImpl.findBy(args)
        elif (userRepository == "JbRepository"):
            return JbRepositoryImpl.findBy(args)
        elif (userRepository == "PasswordsRepository"):
            return PasswordsRepositoryImpl.findBy(args)
        elif (userRepository == "RegisteredClubsRepository"):
            return RegisteredClubsRepositoryImpl.findBy(args)
        elif (userRepository == "RegisteredHotelsRepository"):
            return RegisteredHotelsRepositoryImpl.findBy(args)
        elif (userRepository == "RegisteredJbRepository"):
            return RegisteredJbRepositoryImpl.findBy(args)
        elif (userRepository == "RegisteredTestsRepository"):
            return RegisteredTestsRepositoryImpl.findBy(args)
        elif (userRepository == "RolesRepository"):
            return RolesRepositoryImpl.findBy(args)
        elif (userRepository == "RoomsRepository"):
            return RoomsRepositoryImpl.findBy(args)
        elif (userRepository == "TokensRepository"):
            return TokensRepositoryImpl.findBy(args)
        elif (userRepository == "UsersRepository"):
            return UsersRepositoryImpl.findBy(args)
    @staticmethod
    def findNewId(args):
        userRepository = CheeseRepository.findUserRepository()
        args = CheeseRepository.getTypeOf(args)

        if (userRepository == "BedRepository"):
            return BedRepositoryImpl.findNewId(args)
        elif (userRepository == "ClubsRepository"):
            return ClubsRepositoryImpl.findNewId(args)
        elif (userRepository == "EventsRepository"):
            return EventsRepositoryImpl.findNewId(args)
        elif (userRepository == "HotelsRepository"):
            return HotelsRepositoryImpl.findNewId(args)
        elif (userRepository == "JbRepository"):
            return JbRepositoryImpl.findNewId(args)
        elif (userRepository == "PasswordsRepository"):
            return PasswordsRepositoryImpl.findNewId(args)
        elif (userRepository == "RegisteredClubsRepository"):
            return RegisteredClubsRepositoryImpl.findNewId(args)
        elif (userRepository == "RegisteredHotelsRepository"):
            return RegisteredHotelsRepositoryImpl.findNewId(args)
        elif (userRepository == "RegisteredJbRepository"):
            return RegisteredJbRepositoryImpl.findNewId(args)
        elif (userRepository == "RegisteredTestsRepository"):
            return RegisteredTestsRepositoryImpl.findNewId(args)
        elif (userRepository == "RolesRepository"):
            return RolesRepositoryImpl.findNewId(args)
        elif (userRepository == "RoomsRepository"):
            return RoomsRepositoryImpl.findNewId(args)
        elif (userRepository == "TokensRepository"):
            return TokensRepositoryImpl.findNewId(args)
        elif (userRepository == "UsersRepository"):
            return UsersRepositoryImpl.findNewId(args)
    @staticmethod
    def findBySorted(args):
        userRepository = CheeseRepository.findUserRepository()
        args = CheeseRepository.getTypeOf(args)

        if (userRepository == "EventsRepository"):
            return EventsRepositoryImpl.findBySorted(args)
    @staticmethod
    def login(args):
        userRepository = CheeseRepository.findUserRepository()
        args = CheeseRepository.getTypeOf(args)

        if (userRepository == "PasswordsRepository"):
            return PasswordsRepositoryImpl.login(args)
    @staticmethod
    def findToken(args):
        userRepository = CheeseRepository.findUserRepository()
        args = CheeseRepository.getTypeOf(args)

        if (userRepository == "TokensRepository"):
            return TokensRepositoryImpl.findToken(args)


    @staticmethod
    def save(args):
        userRepository = CheeseRepository.findUserRepository()

        if (userRepository == "BedRepository"):
            return BedRepositoryImpl.save(args)
        elif (userRepository == "ClubsRepository"):
            return ClubsRepositoryImpl.save(args)
        elif (userRepository == "EventsRepository"):
            return EventsRepositoryImpl.save(args)
        elif (userRepository == "HotelsRepository"):
            return HotelsRepositoryImpl.save(args)
        elif (userRepository == "JbRepository"):
            return JbRepositoryImpl.save(args)
        elif (userRepository == "PasswordsRepository"):
            return PasswordsRepositoryImpl.save(args)
        elif (userRepository == "RegisteredClubsRepository"):
            return RegisteredClubsRepositoryImpl.save(args)
        elif (userRepository == "RegisteredHotelsRepository"):
            return RegisteredHotelsRepositoryImpl.save(args)
        elif (userRepository == "RegisteredJbRepository"):
            return RegisteredJbRepositoryImpl.save(args)
        elif (userRepository == "RegisteredTestsRepository"):
            return RegisteredTestsRepositoryImpl.save(args)
        elif (userRepository == "RolesRepository"):
            return RolesRepositoryImpl.save(args)
        elif (userRepository == "RoomsRepository"):
            return RoomsRepositoryImpl.save(args)
        elif (userRepository == "TokensRepository"):
            return TokensRepositoryImpl.save(args)
        elif (userRepository == "UsersRepository"):
            return UsersRepositoryImpl.save(args)
    @staticmethod
    def update(args):
        userRepository = CheeseRepository.findUserRepository()

        if (userRepository == "BedRepository"):
            return BedRepositoryImpl.update(args)
        elif (userRepository == "ClubsRepository"):
            return ClubsRepositoryImpl.update(args)
        elif (userRepository == "EventsRepository"):
            return EventsRepositoryImpl.update(args)
        elif (userRepository == "HotelsRepository"):
            return HotelsRepositoryImpl.update(args)
        elif (userRepository == "JbRepository"):
            return JbRepositoryImpl.update(args)
        elif (userRepository == "PasswordsRepository"):
            return PasswordsRepositoryImpl.update(args)
        elif (userRepository == "RegisteredClubsRepository"):
            return RegisteredClubsRepositoryImpl.update(args)
        elif (userRepository == "RegisteredHotelsRepository"):
            return RegisteredHotelsRepositoryImpl.update(args)
        elif (userRepository == "RegisteredJbRepository"):
            return RegisteredJbRepositoryImpl.update(args)
        elif (userRepository == "RegisteredTestsRepository"):
            return RegisteredTestsRepositoryImpl.update(args)
        elif (userRepository == "RolesRepository"):
            return RolesRepositoryImpl.update(args)
        elif (userRepository == "RoomsRepository"):
            return RoomsRepositoryImpl.update(args)
        elif (userRepository == "TokensRepository"):
            return TokensRepositoryImpl.update(args)
        elif (userRepository == "UsersRepository"):
            return UsersRepositoryImpl.update(args)
    @staticmethod
    def delete(args):
        userRepository = CheeseRepository.findUserRepository()

        if (userRepository == "BedRepository"):
            return BedRepositoryImpl.delete(args)
        elif (userRepository == "ClubsRepository"):
            return ClubsRepositoryImpl.delete(args)
        elif (userRepository == "EventsRepository"):
            return EventsRepositoryImpl.delete(args)
        elif (userRepository == "HotelsRepository"):
            return HotelsRepositoryImpl.delete(args)
        elif (userRepository == "JbRepository"):
            return JbRepositoryImpl.delete(args)
        elif (userRepository == "PasswordsRepository"):
            return PasswordsRepositoryImpl.delete(args)
        elif (userRepository == "RegisteredClubsRepository"):
            return RegisteredClubsRepositoryImpl.delete(args)
        elif (userRepository == "RegisteredHotelsRepository"):
            return RegisteredHotelsRepositoryImpl.delete(args)
        elif (userRepository == "RegisteredJbRepository"):
            return RegisteredJbRepositoryImpl.delete(args)
        elif (userRepository == "RegisteredTestsRepository"):
            return RegisteredTestsRepositoryImpl.delete(args)
        elif (userRepository == "RolesRepository"):
            return RolesRepositoryImpl.delete(args)
        elif (userRepository == "RoomsRepository"):
            return RoomsRepositoryImpl.delete(args)
        elif (userRepository == "TokensRepository"):
            return TokensRepositoryImpl.delete(args)
        elif (userRepository == "UsersRepository"):
            return UsersRepositoryImpl.delete(args)


    @staticmethod
    def initRepositories():
        BedRepositoryImpl.init()
        ClubsRepositoryImpl.init()
        EventsRepositoryImpl.init()
        HotelsRepositoryImpl.init()
        JbRepositoryImpl.init()
        PasswordsRepositoryImpl.init()
        RegisteredClubsRepositoryImpl.init()
        RegisteredHotelsRepositoryImpl.init()
        RegisteredJbRepositoryImpl.init()
        RegisteredTestsRepositoryImpl.init()
        RolesRepositoryImpl.init()
        RoomsRepositoryImpl.init()
        TokensRepositoryImpl.init()
        UsersRepositoryImpl.init()

        pass

    # finds name of user-made repository
    @staticmethod
    def findUserRepository():
        curframe = inspect.currentframe()
        calframe = inspect.getouterframes(curframe, 2)
        userRepository = ResMan.getFileName(calframe[2][1]).replace(".py", "")
        return userRepository

    # convert arguments
    @staticmethod
    def getTypeOf(args):
        newArgs = []
        for arg in args:
            if (type(arg) is str):
                if (len(arg) == 0): newArgs.append("")
                elif (arg[-1] != "\'" 
                    and arg[-1] != ")" 
                    and not arg.endswith("DESC") 
                    and not arg.endswith("ASC")):
                    if (arg.startswith("columnName-")):
                        newArgs.append(arg.replace("columnName-", ""))
                    else:
                        newArgs.append(f"\'{arg}\'")
                else:
                    newArgs.append(str(arg))
            elif (type(arg) is list):
                newArgs.append("(" + ",".join(CheeseRepository.getTypeOf(arg)) + ")")
            elif (type(arg) is datetime):
                newArgs.append("'" + datetime.strftime(arg, "%d-%m-%Y %H:%M:%S") + "'")
            else:
                newArgs.append(str(arg))
        return newArgs

